modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/jaquadro/StorageDrawers/issues"
displayURL="https://minecraft.curseforge.com/projects/storagedrawers"
authors="Texelsaur"
license="MIT"

[[mods]]
    modId="storagedrawers"
    version="8.3.0"
    displayName="Storage Drawers"
    description='''
    Multi-drawer storage blocks for quick storage and retrieval.
    '''

[[dependencies.storagedrawers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    side="BOTH"

[[dependencies.storagedrawers]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.14,)"
    ordering="NONE"
    side="BOTH"
