modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="create_stuff_additions"
version="1.1.5"
displayName="Create Stuff Additions"
credits="credit for Me"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions"
logoFile="logo.png"
authors="Furti_Two"

[[dependencies.create_stuff_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




