modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/tool-stats/issues"
license="LGPL v2.1"

[[mods]]
modId="toolstats"
updateJSONURL="https://updates.blamejared.com/get?n=toolstats&gv=1.16.5"
version="6.0.4"
displayName="ToolStats"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tool-stats"
credits="Thanks to my supporters on Patreon. Rempler, lothrazar, arcanearchivesmod, Pongo Sapiens, Darkosto"
authors="Darkhax"
description='''
Adds tool stats to item tooltips.
'''

[[dependencies.toolstats]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.toolstats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"