modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="dungeons_arise"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}"
displayName="When Dungeons Arise"
displayURL="https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise"
logoFile="wda_logo.png"
credits="Special thanks to MercyWhistles and Wyll for their contributions!"
authors="Aurelj, DiamondTown and Zephyrusj"
description='''
Elegant - and likely dangerous - structures and roguelike dungeons to lose yourself in...
'''

[[dependencies.dungeons_arise]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.dungeons_arise]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="SERVER"
