modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/CreativeMD/PlayerRevive/issues"
logoFile="playerrevive.png"
license="GNU General Public License v3.0"

[[mods]]
	modId="playerrevive"
	version="2.0.0"
	displayName="PlayerRevive"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/playerrevive"
	authors=["CreativeMD"]
	description='''Help your friends in need and revive them'''
	
[[dependencies.itemphysic]]
	modId="creativecore"
	mandatory=true
	ordering="NONE"
	side="BOTH"
	versionRange="[2.0.0,)"