modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/TheIllusiveC4/Champions/issues"
logoFile="champions_icon.png"
license="LGPL-3.0-or-later"
[[mods]]
modId="champions"
version="1.16.5-2.0.1.8"
displayName="Champions"
displayURL="https://www.curseforge.com/minecraft/mc-mods/champions"
authors="C4"
description='''
Creates elite mobs of different rarities, with enhanced stats and extra abilities.
'''
[[dependencies.champions]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.champions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.champions]]
    modId="scalinghealth"
    mandatory=false
    versionRange="[4.1.0,)"
    ordering="NONE"
    side="BOTH"