modLoader="javafml" #mandatory
loaderVersion="[35,)"
license="GPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Strongholds/issues"

[[mods]]
	modId="betterstrongholds"
	version="1.16.4-1.2.1"
	displayName="YUNG's Better Strongholds"
	credits="Thanks so much to all my patrons for their support, and special shoutout to TelepathicGrunt for always helping me out with my mods."
	authors="YUNGNICKYOUNG, Acarii"
	description="A complete redesign of Minecraft's strongholds"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds"

[[dependencies.betterstrongholds]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.betterstrongholds]]
    modId="yungsapi"
    versionRange="[1.16.4-Forge-12,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
