modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="hostilenetworks" #mandatory

version="1.0.4" #mandatory

displayName="Hostile Neural Networks" #mandatory

description='''Defeating hostile entities - but in simulations!'''

[[dependencies.hostilenetworks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.2.19,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.hostilenetworks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hostilenetworks]]
    modId="placebo"
    mandatory=true
    versionRange="[4.6.0,)"
    ordering="NONE"
    side="BOTH"