modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/TheLMiffy1111/JAOPCA/issues"
displayURL="https://minecraft.curseforge.com/projects/jaopca"
credits="Inspired by AOBD, a mod made by ganymedes01 for Minecraft 1.7"
authors="TheLMiffy1111"
[[mods]]
modId="jaopca"
version="${file.jarVersion}"
displayName="JAOPCA"
description="A mod that aims to make mods with ore processing support more ores."

[[dependencies.jaopca]]
    modId="forge"
    mandatory=false
    versionRange="[34.0.0,)"
    ordering="NONE"
    side="BOTH"
