license="All Rights Reserved"
modLoader="javafml"
loaderVersion="[28,)"

logoFile="furnitureslogo.png"
[[mods]]
modId="mcwfurnitures"
version="2.0.1"
displayName="Macaw's Furniture"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures"
updateJSONURL="https://raw.githubusercontent.com/sketchmacaw/macawsmods/master/furniture.json"
credits=""
authors="Sketch Macaw"
description="Store your stuff in various furniture!"

[[dependencies.mcwfurnitures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"