modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="cold_sweat"
version="${file.jarVersion}"
displayName="Cold Sweat"
#logoFile="cold_sweat.png"
authors="iMikul, chubbymomo, skinnymomo"
description='''

'''
[[dependencies.cold_sweat]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.cold_sweat]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
